### ISSUE TITLE
cannot create signed application

### ISSUE THREAD

**Issue by marcusb** [jvoegele/gradle-android-plugin#10]
The plugin cannot create signed application archives. It tries to sign the file specified by  'out.unsigned.package', but nothing creates this file.

**Comment by fdasoghe** [comment]
Did you call the androidPackageRelease?
Or better, can you post your build.gradle file and the command you issue?

**Comment by marcusb** [comment]
Hmm, seems I made a mistake. Sorry about that.

**Comment by fdasoghe** [comment]
Hello.
It seems I'm having your same issue.
Calling task "androidPackageRelease" doesn't create the 'out.unsigned.package'.
For what I see, the reason is that both androidPackageDebug and androidPackageRelease call the apkbuilder ant command, but this (in ApkBuilderTask_r7) create always the output file in out.debug.unaligned.package...

**Comment by marcusb** [comment]
Yes, this issue is valid after all. Please reopen.

**Comment by fdasoghe** [comment]
I think the only one who can reopen the issue is Jason...

Anyway, I think this issue is of broader importance than "only" the creation of release package. For example, it's also related to issue #6 about input and output files (I'm going to write more there).

**Comment by jvoegele** [comment]
I've reopened this issue for investigation.

**Comment by jvoegele** [comment]
I think this has been fixed by think01 in his fork.  I'll get confirmation and apply when he says it's ready.

**Comment by fdasoghe** [comment]
Fixed in 0.9.5. See the README.txt for instructions.
