### ISSUE TITLE
Support the apklib format

### ISSUE THREAD

**Issue by imbeyondboredom** [jvoegele/gradle-android-plugin#100]
While this gradle plugin supports the aar format for library projects, apklib is already present and widely used. Basically by not supporting this format you're excluding a large developer base that would gladly switch to gradle but can't due to legacy dependencies or just the ease of having projects already in the apklib format. 

Without apklib support I will most likely not be able to convince my team (nor myself) to switch to gradle.

Also since the apklib format is just a zip file containing a library project, I'm hoping the effort to extract the project and link to it like a normal library project would not be too difficult.

**Comment by smarek** [comment]
+1

**Comment by derekbrameyer** [comment]
BIG +1.  This is crucial in order to support and use existing Android libraries.  Without apklib support, it is very difficult to use external libraries and manage them well.  We would have to revert to committing library source files with the project, which is a no-go for multi-developer projects.

Waiting for other developers to get around to converting existing libraries to Gradle is going to be incredibly painful, and going through and altering existing projects to add Gradle build properties is tedious.  Solving this issue by allowing for apklib from the plugin would be a great solution.

**Comment by mrmans0n** [comment]
+1 here.

I can't convince our team to switch to gradle if we lose all compatibility from all the apklibs we use (a lot of internal ones too). And it seems maven-android-plugin is implementing aar support right now, so that makes this even harder :(
