### ISSUE TITLE
More verbose logging

### ISSUE THREAD

**Issue by mttkay** [jvoegele/gradle-android-plugin#18]
Currently it's difficult (if impossible) to see what gradle-android is doing in each build step. I would like to see an option for more verbose output, probably best by increasing the log output when invoked via Gradle's -i flag (info logging).

Particularly, that level of verbosity should tell the user which command gradle-android invoked under the hoods, similar to how maven-android-plugin does it (it will output e.g. the full path to the tool being used, plus arguments passed to it).

Moreover, failures when communicating with the device should bubble up to the user even without verbose logging. For instance, it is at the moment impossible to detect why the build locks up when there is more than one device running, and no ant.adb.args parameter was passed to the build script.

**Comment by Ladicek** [comment]
The case of multiple attached devices should be pretty easy to detect. I have been thinking about solving it since you mentioned it in the other issue and came with this idea:

Since Gradle doesn't (easily) support cmdline arguments (yet), maybe we could dynamically create separate variant of androidInstall (and uninstall) task for each device, named e.g. androidInstallEmulator or something like that. The default androidInstall task would still be there and work as usual in case of single attached device. In case of multiple attached devices, it would fail and list available tasks.

What do you think about that?

**Comment by mttkay** [comment]
Not sure if that will help -- a build server may have several emulators running, so you'd still have to route the -s option to ADB to target a specific device. Can we maybe supply a property that is nicer to use than `-Dadb.device.args="-s emulator-5554"`?

**Comment by mttkay** [comment]
How about this:

`-Ddevice=emulator` --> resolves to `adb -e`

`-Ddevice=device` --> resolves to `adb -d`

`-Ddevice=XXXXX` -> resolves to `adb -s XXXXX`

**Comment by Ladicek** [comment]
Pretty much the same I was thinking about -- the only thing different is that you suggest using an environment variable whereas I suggest using different task names. I guess that env vars are better for configuring an automated build system, while task names would be easier for running build by hand (especially if you use Gradle's "task name shortening" capability, e.g. instead of writing "gradle androidInstall", you only write "gradle anIn").

Since using env vars doesn't need listing available devices (if you set it wrong, you just set it wrong and get error message from adb), I'll probably stick with it. Thanks for the idea.

**Comment by mttkay** [comment]
true -- I see what you mean. Alternatively, it could provide both, and tasks such as androidInstallEmulator would merely configure the environment to do the right thing. That way one can decide which way to use.

Generally, I don't have a strong opinion about this, but I'm a fan of slim interfaces, and we should probably think twice about increasing the number of tasks facing the user. Moreover, remember that -s/-d/-e not only affect the install command, they affect anything done via adb (e.g. we will need it again when using the activity manager `adb am` to run instrumentations), so using tasks to steer this would quickly explode the number of tasks exposed by gradle-android.

**Comment by Ladicek** [comment]
You're right. I am not an experienced Android developer, so I didn't even think of "adb am" stuff. Such combinatorial explosion would be hell. Using env var (and maybe declaring default in the buildscript?) is probably the way to go.

**Comment by fdasoghe** [comment]
Hello.

I've created a Google Code hosting for this project, and two linked Google Groups (user and developer).The intent is to use Google's facilities for every aspect regarding discussions, issue tracking, documentation, wiki, and keeping using GitHub for source code repository, forking and merging.

The project is here: http://code.google.com/p/gradle-android-plugin/

Please, don't open new issues on GitHub but on the new hosting project.

Cheers,

Fabio

**Comment by mttkay** [comment]
great, thanks!
